// SPDX-License-Identifier: MIT
// Copyright (c) 3va contributors

use crate::lockfile::{Lockfile, LockfileDep, LockfilePackage};
use std::collections::HashMap;

// ── Yarn v1 lockfile parser ────────────────────────────────────────────────────
//
// Format (simplified):
//
//   # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
//   # yarn lockfile v1
//
//   lodash@^4.17.21:
//     version "4.17.21"
//     resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#..."
//     integrity sha512-...
//     dependencies:
//       dep-name "^1.0.0"
//
//   "express@^4.18.0", express@^4.18.0:
//     version "4.18.2"
//     ...

/// Parse a yarn.lock v1 file content into key → entry map.
fn flush_yarn_entry(
    entries: &mut HashMap<String, YarnEntry>,
    keys: Vec<String>,
    entry: YarnEntryBuilder,
) {
    let built = entry.build();
    for key in keys {
        entries.insert(
            key,
            YarnEntry {
                version: built.version.clone(),
                resolved: built.resolved.clone(),
                integrity: built.integrity.clone(),
                dependencies: built.dependencies.clone(),
            },
        );
    }
}

fn parse_yarn_entries(content: &str) -> HashMap<String, YarnEntry> {
    let mut entries = HashMap::new();
    let mut current_keys: Option<Vec<String>> = None;
    let mut current_entry: Option<YarnEntryBuilder> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip comments and blank lines
        if trimmed.is_empty() || trimmed.starts_with('#') {
            if let (Some(keys), Some(entry)) = (current_keys.take(), current_entry.take()) {
                flush_yarn_entry(&mut entries, keys, entry);
            }
            continue;
        }

        if line.starts_with(' ') || line.starts_with('\t') {
            // Continuation line (indented)
            if line.starts_with("  ") || line.starts_with('\t') {
                let content = trimmed;
                if let Some(ref mut entry) = current_entry {
                    if let Some(rest) = content.strip_prefix("version ") {
                        entry.version = Some(rest.trim_matches('"').to_string());
                    } else if let Some(rest) = content.strip_prefix("resolved ") {
                        entry.resolved = Some(rest.trim_matches('"').to_string());
                    } else if let Some(rest) = content.strip_prefix("integrity ") {
                        entry.integrity = Some(rest.trim_matches('"').to_string());
                    } else if content == "dependencies:" {
                        entry.in_deps = true;
                    } else if content == "optionalDependencies:" {
                        entry.in_opt_deps = true;
                    } else if entry.in_deps || entry.in_opt_deps {
                        // dependency line: "  dep-name "^1.0.0""
                        if let Some(eq_pos) = content.find(' ') {
                            let dep_name = content[..eq_pos].trim().trim_matches('"').to_string();
                            let dep_ver = content[eq_pos..].trim().trim_matches('"').to_string();
                            entry.dependencies.entry(dep_name).or_insert(dep_ver);
                        }
                    }
                }
            }
        } else {
            // Save previous entry
            if let (Some(keys), Some(entry)) = (current_keys.take(), current_entry.take()) {
                flush_yarn_entry(&mut entries, keys, entry);
            }

            // New entry: key line like "lodash@^4.17.21:" or "\"@scope/pkg@^1.0.0\":"
            let key_line = trimmed.trim_end_matches(':');
            current_keys = Some(split_yarn_keys(key_line));
            current_entry = Some(YarnEntryBuilder::new());
        }
    }

    // Flush last entry
    if let (Some(keys), Some(entry)) = (current_keys.take(), current_entry.take()) {
        flush_yarn_entry(&mut entries, keys, entry);
    }

    entries
}

fn split_yarn_keys(line: &str) -> Vec<String> {
    let mut keys = Vec::new();
    let mut depth = 0u32;
    let mut start = 0usize;

    for (i, ch) in line.char_indices() {
        match ch {
            '"' => depth ^= 1,
            ',' if depth == 0 => {
                let key = line[start..i].trim().trim_matches('"').to_string();
                if !key.is_empty() {
                    keys.push(key);
                }
                start = i + 1;
            }
            _ => {}
        }
    }

    let last = line[start..].trim().trim_matches('"').to_string();
    if !last.is_empty() {
        keys.push(last);
    }

    keys
}

struct YarnEntryBuilder {
    version: Option<String>,
    resolved: Option<String>,
    integrity: Option<String>,
    dependencies: HashMap<String, String>,
    in_deps: bool,
    in_opt_deps: bool,
}

impl YarnEntryBuilder {
    fn new() -> Self {
        Self {
            version: None,
            resolved: None,
            integrity: None,
            dependencies: HashMap::new(),
            in_deps: false,
            in_opt_deps: false,
        }
    }

    fn build(self) -> YarnEntry {
        YarnEntry {
            version: self.version.unwrap_or_else(|| "0.0.0".to_string()),
            resolved: self.resolved,
            integrity: self.integrity,
            dependencies: self.dependencies,
        }
    }
}

struct YarnEntry {
    version: String,
    resolved: Option<String>,
    integrity: Option<String>,
    dependencies: HashMap<String, String>,
}

/// Extract the package name from a yarn key like `"lodash@^4.17.21"` or
/// `"@scope/pkg@1.0.0"`.  The package name is everything before the last `@`.
fn extract_name_from_key(key: &str) -> String {
    // Handle scoped packages: @scope/pkg@version
    if key.starts_with('@')
        && let Some(rest) = key.strip_prefix('@')
        && let Some(slash_pos) = rest.find('/')
    {
        let scope_end = 1 + slash_pos;
        let after_scope = &key[scope_end + 1..];
        if let Some(at_pos) = after_scope.rfind('@') {
            return format!("@{}", &rest[..=slash_pos + at_pos]);
        }
        return key.to_string();
    }

    // Regular package: name@version
    if let Some(at_pos) = key.rfind('@') {
        key[..at_pos].to_string()
    } else {
        key.to_string()
    }
}

// ── Public API ─────────────────────────────────────────────────────────────────

/// Which generation a `yarn.lock` was written by.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum YarnGeneration {
    /// Yarn v1 — a flat `name@range:` list. Fully convertible.
    Classic,
    /// Yarn 2+ ("Berry") — YAML with a `__metadata:` block. **Not**
    /// convertible: its `checksum` is a Yarn cache key, not an SRI integrity
    /// hash, so a lockfile built from it would fail verification on every
    /// package. Silently "migrating" it produced entries with version `0.0.0`
    /// and no integrity, which is worse than refusing.
    Berry,
}

/// Detect the generation from the file's own header.
pub fn classify(content: &str) -> YarnGeneration {
    if content.contains("__metadata:") {
        return YarnGeneration::Berry;
    }
    // Berry writes a YAML comment header naming itself; v1 writes
    // "# yarn lockfile v1" and nothing else structured.
    for line in content.lines().take(5) {
        if line
            .trim()
            .starts_with("# This file is generated by running \"yarn install\"")
        {
            return YarnGeneration::Berry;
        }
    }
    YarnGeneration::Classic
}

/// Load a lockfile from Yarn v1's `yarn.lock` format.
///
/// Returns `None` if the file doesn't exist or is a Berry lockfile.
pub fn load_from_yarn_lock(path: &std::path::Path) -> anyhow::Result<Option<Lockfile>> {
    if !path.exists() {
        return Ok(None);
    }
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("Cannot read {}: {}", path.display(), e))?;

    if classify(&content) == YarnGeneration::Berry {
        return Ok(None);
    }

    let entries = parse_yarn_entries(&content);
    if entries.is_empty() {
        return Ok(None);
    }

    let mut packages = HashMap::new();
    let mut dependencies = HashMap::new();

    packages.insert(
        String::new(),
        LockfilePackage {
            version: "0.0.0".to_string(),
            resolved: None,
            integrity: None,
            dev: None,
            registry: None,
        },
    );

    for (key, entry) in &entries {
        let pkg_name = extract_name_from_key(key);

        packages.insert(
            format!("node_modules/{}", pkg_name),
            LockfilePackage {
                version: entry.version.clone(),
                resolved: entry.resolved.clone(),
                integrity: entry.integrity.clone(),
                dev: None,
                registry: None,
            },
        );

        dependencies.entry(pkg_name).or_insert_with(|| {
            let deps = if entry.dependencies.is_empty() {
                None
            } else {
                Some(entry.dependencies.clone())
            };
            LockfileDep {
                version: entry.version.clone(),
                resolved: entry.resolved.clone(),
                integrity: entry.integrity.clone(),
                dependencies: deps,
                dev: None,
                registry: None,
            }
        });
    }

    Ok(Some(Lockfile {
        lockfile_version: 0,
        name: path
            .parent()
            .and_then(|p| {
                let pkg = p.join("package.json");
                std::fs::read_to_string(pkg).ok().and_then(|c| {
                    serde_json::from_str::<serde_json::Value>(&c)
                        .ok()
                        .and_then(|v| v["name"].as_str().map(String::from))
                })
            })
            .unwrap_or_else(|| "yarn-project".to_string()),
        version: "0.0.0".to_string(),
        packages,
        dependencies,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn classifies_v1_as_classic() {
        let v1 = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\nlodash@^4.17.21:\n  version \"4.17.21\"\n";
        assert_eq!(classify(v1), YarnGeneration::Classic);
    }

    #[test]
    fn classifies_berry_by_its_metadata_block() {
        let berry = "# This file is generated by running \"yarn install\" inside your project.\n\n__metadata:\n  version: 8\n  cacheKey: 10c0\n\n\"lodash@npm:^4.17.21\":\n  version: 4.17.21\n  resolution: \"lodash@npm:4.17.21\"\n  checksum: 10c0/abc\n";
        assert_eq!(classify(berry), YarnGeneration::Berry);
    }

    #[test]
    fn a_berry_lockfile_is_refused_rather_than_mangled() {
        let dir = TempDir::new().unwrap();
        let p = dir.path().join("yarn.lock");
        std::fs::write(
            &p,
            "# This file is generated by running \"yarn install\" inside your project.\n\n__metadata:\n  version: 8\n\n\"lodash@npm:^4.17.21\":\n  version: 4.17.21\n  resolution: \"lodash@npm:4.17.21\"\n  checksum: 10c0/abc\n",
        )
        .unwrap();
        // Every version used to come out as 0.0.0 with a null integrity, which
        // reads as a valid-but-empty lockfile and diverges from the real tree.
        assert!(load_from_yarn_lock(&p).unwrap().is_none());
    }

    #[test]
    fn parse_simple_yarn_lock() {
        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#hash"
  integrity sha512-fakehash

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz#hash"
  integrity sha512-fakehash2
  dependencies:
    accepts "^1.3.8"
"#;

        let entries = parse_yarn_entries(content);
        assert!(entries.contains_key("lodash@^4.17.21"));
        assert!(entries.contains_key("express@^4.18.0"));
        assert_eq!(entries["lodash@^4.17.21"].version, "4.17.21");
        assert!(
            entries["express@^4.18.0"]
                .dependencies
                .contains_key("accepts")
        );
        assert_eq!(entries["express@^4.18.0"].dependencies["accepts"], "^1.3.8");
    }

    #[test]
    fn parse_scoped_package_yarn_lock() {
        let content = r#"# yarn lockfile v1

"@babel/core@^7.24.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz#hash"
  integrity sha512-fake
  dependencies:
    "@babel/helper-plugin-utils" "^7.24.0"
"#;

        let entries = parse_yarn_entries(content);
        assert!(entries.contains_key("@babel/core@^7.24.0"));
        assert_eq!(entries["@babel/core@^7.24.0"].version, "7.24.0");
    }

    #[test]
    fn extract_name_from_key_scoped() {
        assert_eq!(extract_name_from_key("@babel/core@^7.24.0"), "@babel/core");
        assert_eq!(extract_name_from_key("@scope/pkg@1.0.0"), "@scope/pkg");
    }

    #[test]
    fn extract_name_from_key_regular() {
        assert_eq!(extract_name_from_key("lodash@^4.17.21"), "lodash");
        assert_eq!(extract_name_from_key("express@4.18.2"), "express");
    }

    #[test]
    fn load_from_yarn_lock_nonexistent() {
        let result = load_from_yarn_lock(std::path::Path::new("/nonexistent/yarn.lock")).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn load_from_yarn_lock_file() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("yarn.lock");
        std::fs::write(
            &path,
            r#"# yarn lockfile v1
axios@^1.7.0:
  version "1.7.9"
  resolved "https://registry.yarnpkg.com/axios/-/axios-1.7.9.tgz#hash"
  integrity sha512-test
"#,
        )
        .unwrap();

        // Create package.json so name gets picked up
        std::fs::write(
            dir.path().join("package.json"),
            r#"{"name":"my-project","version":"1.0.0"}"#,
        )
        .unwrap();

        let result = load_from_yarn_lock(&path).unwrap();
        assert!(result.is_some());
        let lock = result.unwrap();
        assert!(lock.dependencies.contains_key("axios"));
        assert_eq!(lock.dependencies["axios"].version, "1.7.9");
    }

    #[test]
    fn parse_multi_key_yarn_entry() {
        let content = r#"# yarn lockfile v1

"eslint@^8.0.0", eslint@^8.0.0:
  version "8.57.0"
  resolved "https://registry.yarnpkg.com/eslint/-/eslint-8.57.0.tgz#hash"
  integrity sha512-fake
"#;

        let entries = parse_yarn_entries(content);
        assert!(entries.contains_key("eslint@^8.0.0"));
        assert_eq!(entries["eslint@^8.0.0"].version, "8.57.0");
    }
}
